# Generated by Django 4.2.10 on 2024-02-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'クライアント',
                'verbose_name_plural': 'クライアント',
            },
        ),
        migrations.CreateModel(
            name='PlaySetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Hard')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.client')),
            ],
            options={
                'verbose_name': 'プレイ設定',
                'verbose_name_plural': 'プレイ設定',
            },
        ),
    ]
